In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('akarpov_37659/hm_1_heart_disease_classification/heart_disease_data/HeartDiseaseData.csv')

In [3]:
data.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>ID</th>
      <th>Age</th>
      <th>Sex</th>
      <th>cp</th>
      <th>trestbps</th>
      <th>chol</th>
      <th>fbs</th>
      <th>restecg</th>
      <th>thalach</th>
      <th>exang</th>
      <th>oldpeak</th>
      <th>num</th>
      <th>Place</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>1</td>
      <td>28</td>
      <td>male</td>
      <td>atypical angina</td>
      <td>130.0</td>
      <td>132.0</td>
      <td>False</td>
      <td>showing probable or definite left ventricular ...</td>
      <td>185.0</td>
      <td>no</td>
      <td>0.0</td>
      <td>0</td>
      <td>Hungary</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>2</td>
      <td>29</td>
      <td>male</td>
      <td>atypical angina</td>
      <td>120.0</td>
      <td>243.0</td>
      <td>False</td>
      <td>normal</td>
      <td>160.0</td>
      <td>no</td>
      <td>0.0</td>
      <td>0</td>
      <td>Hungary</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>3</td>
      <td>29</td>
      <td>male</td>
      <td>atypical angina</td>
      <td>140.0</td>
      <td>NaN</td>
      <td>False</td>
      <td>normal</td>
      <td>170.0</td>
      <td>no</td>
      <td>0.0</td>
      <td>0</td>
      <td>Hungary</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>4</td>
      <td>30</td>
      <td>female</td>
      <td>typical angina</td>
      <td>170.0</td>
      <td>237.0</td>
      <td>False</td>
      <td>having ST-T wave abnormality (T wave inversion...</td>
      <td>170.0</td>
      <td>no</td>
      <td>0.0</td>
      <td>0</td>
      <td>Hungary</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>5</td>
      <td>31</td>
      <td>female</td>
      <td>atypical angina</td>
      <td>100.0</td>
      <td>219.0</td>
      <td>False</td>
      <td>having ST-T wave abnormality (T wave inversion...</td>
      <td>150.0</td>
      <td>no</td>
      <td>0.0</td>
      <td>0</td>
      <td>Hungary</td>
    </tr>
  </tbody>
</table>
</div>